### ISSUE TITLE
Data protection policy

### ISSUE THREAD

**Issue by chartgerink** [libscie/legal#3]
We need to make sure to add data protection policies. We're not collecting any data at the moment, but with Hypergraph Vault being prepared it is becoming more urgent.

**Comment by jameslibscie** [comment]
@chartgerink Is this issue intended for the Vault only or also the website?

**Comment by chartgerink** [comment]
This is upstream for the Vault and serves as the main reference. This will be for the Liberate Science website first, and if we use different versions downstream we'll be adding specific texts later.

**Comment by chartgerink** [comment]
This is covered in the Terms, so closing this.
